version = 0.1

[prod.deploy.parameters]
stack_name = "social-charger-club-prod"
resolve_s3 = true
s3_prefix = "social-charger-club-prod"
region = "eu-west-2"
profile = "ev-prod"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
image_repositories = []

[dev.deploy.parameters]
stack_name = "social-charger-club-dev"
resolve_s3 = true
s3_prefix = "social-charger-club-dev"
region = "eu-west-2"
profile = "ev-dev"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
