/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:6a681fe3-0463-4672-9235-03b75e91f5e2",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_4RRLvXgC9",
    "aws_user_pools_web_client_id": "30togvmu5drr9ngbs9o6kpvvnb",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ], 
    "aws_api_gateway_url": "https://hqxycm6gxf.execute-api.eu-west-2.amazonaws.com/prod"

};


export default awsmobile;
